export const TESTDATA = {
    email: 'agv417@gmail.com',
    password1: 'P@ssw0rd',
    // url: 'https://todoist.com/auth/login',
    //ESCENARIO 1 url: 'https://demoqa.com/text-box',
    // url: 'https://demoqa.com/text-box',
    // url2: 'https://demoqa.com/webtables',
    // url3: 'https://demoqa.com/automation-practice-form',
    // url4: 'https://demoqa.com/books',
    // userName: 'Maria',
    // password:  'Maria123456*',
    //apiUrl: 'https://api.todoist.com/rest/v2/',
    //apiToken: 'd574c2359cb59a80ac4fbfa4a2fcdf38a58cf06e',
    
    url1: process.env.URL1,
    url2: process.env.URL2,
    url3: process.env.URL3,
    url4: process.env.URL4,
    userName: process.env.USERNAME,
    password: process.env.PASSWORD,
}